language: go
go:
  - 1.5.4
  - 1.6.3
script:
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.3.2/bin/gpm > gpm
  - chmod +x gpm
  - ./gpm install
  - ./test.sh
sudo: false
notifications:
  email: false

